/**
 * Created by chenzhe on 2019/3/27.
 */
import Vue from 'vue';
import Dialog from 'element-ui/lib/dialog';
// 不直接全局注册el-pagination，做了二次封装，全局注册新的pagination组件
// import Pagination from 'element-ui/lib/pagination';
import Pagination from '../../components/Pagination/index.js';

import Menu from 'element-ui/lib/menu';
import Submenu from 'element-ui/lib/submenu';
import MenuItem from 'element-ui/lib/menu-item';
import Button from 'element-ui/lib/button';
import ButtonGroup from 'element-ui/lib/button-group';
import Input from 'element-ui/lib/input';
import InputNumber from 'element-ui/lib/input-number';
import Radio from 'element-ui/lib/radio';
import RadioGroup from 'element-ui/lib/radio-group';
import RadioButton from 'element-ui/lib/radio-button';
import Checkbox from 'element-ui/lib/checkbox';
import CheckboxGroup from 'element-ui/lib/checkbox-group';
import CheckboxButton from 'element-ui/lib/checkbox-button';
import Select from 'element-ui/lib/select';
import Switch from 'element-ui/lib/switch';
import Option from 'element-ui/lib/option';
import Table from 'element-ui/lib/table';
import TableColumn from 'element-ui/lib/table-column';
import DatePicker from 'element-ui/lib/date-picker';
import Tooltip from 'element-ui/lib/tooltip';
import Form from 'element-ui/lib/form';
import FormItem from 'element-ui/lib/form-item';
import Container from 'element-ui/lib/container';
import Header from 'element-ui/lib/header';
import Aside from 'element-ui/lib/aside';
import Main from 'element-ui/lib/main';
import Footer from 'element-ui/lib/footer';
import Dropdown from 'element-ui/lib/dropdown';
import DropdownMenu from 'element-ui/lib/dropdown-menu';
import DropdownItem from 'element-ui/lib/dropdown-item';
import Loading from 'element-ui/lib/loading';
import Tabs from 'element-ui/lib/tabs';
import TabPane from 'element-ui/lib/tab-pane';
import Tree from 'element-ui/lib/tree';
import Message from 'element-ui/lib/message';
import MessageBox from 'element-ui/lib/message-box';
import Row from 'element-ui/lib/row';
import Col from 'element-ui/lib/col';
import Tag from 'element-ui/lib/tag';
import Cascader from 'element-ui/lib/cascader';
import Upload from 'element-ui/lib/upload';
import Steps from 'element-ui/lib/steps';
import Step from 'element-ui/lib/step';
import Calendar from 'element-ui/lib/calendar';
import TimePicker from 'element-ui/lib/time-picker';
import Divider from 'element-ui/lib/divider';
import Alert from 'element-ui/lib/alert';
import Timeline from 'element-ui/lib/timeline';
import TimelineItem from 'element-ui/lib/timeline-item';
import Backtop from 'element-ui/lib/backtop';
import Icon from 'element-ui/lib/icon';
import Carousel from 'element-ui/lib/carousel';
import CarouselItem from 'element-ui/lib/carousel-item';
import Progress from 'element-ui/lib/progress';
import CollapseTransition from 'element-ui/lib/transitions/collapse-transition';


Vue.use(Pagination);
Vue.use(Dialog);
Vue.use(Dropdown);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Menu);
Vue.use(Submenu);
Vue.use(MenuItem);
// Vue.use(MenuItemGroup);
Vue.use(Input);
Vue.use(InputNumber);
Vue.use(Radio);
Vue.use(RadioGroup);
Vue.use(RadioButton);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
Vue.use(CheckboxButton);
Vue.use(Switch);
Vue.use(Select);
Vue.use(Option);
// Vue.use(OptionGroup);
Vue.use(Button);
Vue.use(ButtonGroup);
Vue.use(Table);
Vue.use(TableColumn);
Vue.use(DatePicker);
// // Vue.use(TimeSelect);
Vue.use(TimePicker);
// Vue.use(Popover);
Vue.use(Tooltip);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Tag);
Vue.use(Tree);
Vue.use(Alert);
Vue.use(Backtop);
Vue.use(Row);
Vue.use(Col);
Vue.use(Upload);
Vue.use(Steps);
Vue.use(Step);
Vue.use(Cascader);
Vue.use(Container);
Vue.use(Header);
Vue.use(Aside);
Vue.use(Main);
Vue.use(Footer);
Vue.use(Divider);
Vue.use(Calendar);
Vue.use(Timeline);
Vue.use(TimelineItem);
Vue.use(Icon);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Progress);
Vue.component(CollapseTransition.name, CollapseTransition);

Vue.use(Loading.directive);

Vue.prototype.$loading = Loading.service;
// Vue.prototype.$msgbox = MessageBox;
// Vue.prototype.$alert = MessageBox.alert;
Vue.prototype.$confirm = MessageBox.confirm;
// Vue.prototype.$prompt = MessageBox.prompt;
// Vue.prototype.$notify = Notification;
Vue.prototype.$message_success = mes => Message.success({showClose: false, message: mes,duration:900});
Vue.prototype.$message = Message;

// import '../../sass/pages/index/element-variables.scss';
